### ISSUE TITLE
Add affiliate partner dashboard

### ISSUE THREAD

**Issue by jgoedde** [tutao/tutanota#7529]

**Comment by jgoedde** [comment]
Possibly we could reduce the width of the date cells to only span the actual width of the text.

## Actual:
![image](https://github.com/user-attachments/assets/eb6e9a43-e709-473f-9bed-7f9eda3f430f)

## Expected
![image](https://github.com/user-attachments/assets/235e5b08-b8bd-4857-8392-a06404bc349d)

```css
tr.selectable:nth-child(1) > td:nth-child(1) {
  width: 10%
}
```
should do the trick.
